[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "postgenesis"
version = "0.1.0"
description = "Post-processing for Genesis"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "duoxup" }]
dependencies = [
  "numpy",
  "scipy",
  "matplotlib",
  "imageio>=2.28",
  "tqdm",
  "pandas",
  "h5py",
]

[project.optional-dependencies]
dev = ["pytest", "ruff", "black", "ipykernel"]
viz = ["matplotlib", "imageio"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["postgenesis*"]

[tool.ruff]
line-length = 100
